### ISSUE TITLE
Support frame interpolation

### ISSUE THREAD

**Issue by IceHismxx** [lhc70000/iina#125]
I enjoy watching anime with 60 fps and i know mpv supports frame interpolation natively or with open source stuff like vapoursynth.  Is it possible to add this to iina?

**Comment by lhc70000** [comment]
IINA supports almost all mpv options.

If you are already a mpv user, you may continue using all your configs and scripts by checking "use config directory" in Preference -> Advanced.

If you don't use config files, you can also add following options in Preference -> Advanced to get it work:
```
interpolation=yes
```
See [mpv documentation](https://mpv.io/manual/stable/#options-interpolation) for more information.

According to documentation, you may also need to set
```
video-sync=display-resample
```
or any other `display-` value. 

However please note that `video-sync` may not work correctly in v0.0.1. This problem has been fixed and v0.0.2 will be available in few days.

**Comment by Cellane** [comment]
To support advanced motion interpolation, people often resort to compiling mpv with Vapoursynth support and then supplying own MVTools script or plugging tools like SmoothVideo Project. According to [this thread](http://www.svp-team.com/forum/viewtopic.php?id=3758) on SVP forums, there would theoretically be no problem with enhancing the video with SVP if the mpv binary shipped with IINA were compiled with Vapoursynth support. Is that something that seems reasonable or doable?

**Comment by HarukaMa** [comment]
For SVP support, please refer to #118.

iPhoneから送信

H29/01/15 23:54、Milan Vít <notifications@github.com> のメッセージ:

**Comment by inflation** [comment]
Well, the `video-sync=display-resample` breeks in the new rendering mechanism. 
![screen shot 2017-01-28 at 8 12 10 pm](https://cloud.githubusercontent.com/assets/2375962/22449769/29b54c16-e730-11e6-9786-7bc54865c34a.png)
![screen shot 2017-01-28 at 8 14 13 pm](https://cloud.githubusercontent.com/assets/2375962/22449775/2de42cd0-e730-11e6-9a40-c6518d21b267.png)
Here is a comparation between mpv and iina.

**Comment by bodayw** [comment]
Any updates on fixing ``interpolation``?

Just tried it on 0.0.12 build 37 and it is still not working.

**Comment by jnozsc** [comment]
@bodayw would you mind sharing how you test it on iina?
I would like to follow up on this.

`interpolation` is the most important feature from `mpv`, and the major reason I choose `mpv` for now

**Comment by bodayw** [comment]
@jnozsc I always test it with a video clip that has a panning shot (e.g. the NCED of Carnival Phantasm) and judge by eye. On a 60 Hz monitor playing 24 fps video without interpolation, the judder should be obvious if you know what to look at.

You can probably also see if the estimated FPS reported in ``stats.lua`` is too high, as shown above, also mentioned in #741. #1542 might also be related.

**Comment by inflation** [comment]
Should be fixed in `develop` with #1542.

**Comment by thericeking** [comment]
Sorry to necro this thread but I am new to INNA and MPV. Is there an easy way to enable motion interpolation? I have no clue what to do with the instructions provided here.
