### ISSUE TITLE
BUG report and some suggestions

### ISSUE THREAD

**Issue by Wanguy** [lhc70000/iina#202]
After a period of time of use and found the following issues.

- screen controller will not automatically hide when the screen is reawakened.

- Unable to control volume by touch gesture sometime.

- Program crash when the first running sometime.

and there are some suggestions

- Add preview icon for .mkv.

- Add a feature that the player can remember the last playback progress if someone closes the play window.

- Add a check update button in the setting or the about to get more attention.

**Comment by HarukaMa** [comment]
Please avoid using ALL CAPS in title, thanks. (In case you don't know it is generally considered rude.

Also, please try to search for issues / pull requests before actually raising an issue to avoid duplicates.

I suppose the crash on start issue is fixed in the latest code base.

**Comment by Wanguy** [comment]
I'm sorry, I really don't know that all caps will cause trouble for others, has been corrected.
The problem crash still exists.

**Comment by HarukaMa** [comment]
The bleeding edge bug fixes won't reflect on release builds automatically; I'd suggest testing the nightly version to see if the problem is already fixed...

**Comment by lhc70000** [comment]
> screen controller will not automatically hide when the screen is reawakened.

Is it in fullscreen mode?

> Unable to control volume by touch gesture sometime.

Does the gesture simply do nothing? How about horizontal scrolling?

> Program crash when the first running sometime.

Should have been fixed in develop branch, please wait for next version.

> Add preview icon for .mkv.

Duplicate with #36.

> Add a feature that the player can remember the last playback progress if someone closes the play window.

Added in develop branch, please wait for next version.

> Add a check update button in the setting or the about to get more attention.

It's not a common practice to do so, and IINA will also check update automatically when launched.

**Comment by Wanguy** [comment]
> Is it in fullscreen mode?
Yes, and only in fullscreen mode.
>Does the gesture simply do nothing? How about horizontal scrolling?
No, the gesture simply can be used, but the horizontal scrolling is not.
> Duplicate with #36.
I'm sry, I don't understand but I'll keep trying later.

My device and system version is:
MacBook Pro (Retina 15-inch mid 2015)
macOS Sierra version 10.12.2

I hope I can help solve the problem.

**Comment by alejx** [comment]
> screen controller will not automatically hide when the screen is reawakened.

Cannot reproduce. Does it still exists in the latest version? If so, can you provide more information about that?
