### ISSUE TITLE
Some UI glitches in the localized version 

### ISSUE THREAD

**Issue by euf** [lhc70000/iina#692]
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9
- Russian translation from #686 

**Expected behavior:**

Settings window resizes correctly, and UI elements do not move, overlap or behave strange.

**Actual behavior:**

There are some UI problems, which came out while testing Russian translation. (I posted them to Slack, but got no response.) The problems are the following:

1) While selecting "Codec" tab or "Advanced" tab, the whole tab bar becomes too narrow and the last tab hides under "**>>**" icon.
![2017-05-30 0 34 17](https://cloud.githubusercontent.com/assets/11754264/26562558/e96f1198-44cf-11e7-89ba-a1f4d853d206.png)

2) Alignment of the picture and some elements on the "UI" tab looks weird.
![2017-05-30 0 36 16](https://cloud.githubusercontent.com/assets/11754264/26562588/4d72d1d4-44d0-11e7-8565-931876dcfd38.png)

3) On the "Subtitles" tab dropdown menus for X and Y are too narrow for Russian term "Center" ("По центру"), and truncation of such a little word looks bad.
![2017-05-30 0 39 49](https://cloud.githubusercontent.com/assets/11754264/26562652/e4ee4732-44d0-11e7-8f96-07730740b515.png)

4) The placement of buttons in the "Login to Opensubtitles" window looks too much offset to the right, so the window looks inaccurate.
![2017-05-30 0 42 53](https://cloud.githubusercontent.com/assets/11754264/26562665/0c5aae82-44d1-11e7-89bf-6924b3459924.png)

5) At the "Network" tab spacing between "User agent" ("Юзер-агент") and its corresponding input field is too big. The same for "HTTP proxy" ("HTTP-прокси"). 
![2017-05-30 0 45 12](https://cloud.githubusercontent.com/assets/11754264/26562720/9a5f7ba4-44d1-11e7-8ed1-b066b8747f23.png)

6) At the "Control" tab almost every dropdown menu is too narrow for the Russian term (compare "Hide OSC" and "Скрыть экранное меню"), and again — truncating two or three symbols does not look good. Moreover, there is a strange spacing on the right side.
![2017-05-30 0 48 41](https://cloud.githubusercontent.com/assets/11754264/26562773/485b9cd8-44d2-11e7-972e-c79ff3a573ce.png)

7) At the "Video" quick settings tab the aspect ratio input field is overlapping the selector.
![overlap](https://cloud.githubusercontent.com/assets/11754264/26562417/b8f1707a-44ce-11e7-9728-eb971e44b3de.png)

8) At the font selector window three labels are too narrow for Russian words.
![2017-05-30 1 27 47](https://cloud.githubusercontent.com/assets/11754264/26563241/b7b482de-44d7-11e7-92f4-242fe14d2e8b.png)

All these window constraints placement problems occur with Russian localization even after continuous and painful research of as short words as possible :slightly_smiling_face:

**Comment by skyline75489** [comment]
2 and 8 seems to be already fixed in develop branch.

**Comment by fabi94music** [comment]
I noticed similar UI glitches in German: 
![bildschirmfoto 2017-09-01 12 58 26](https://user-images.githubusercontent.com/29753374/29967100-41c40710-8f15-11e7-9e38-a1b46a182a8e.jpg)

**Comment by alejx** [comment]
The preferences panel has been heavily redesigned in develop branch. Check it and you can report in this thread if find anything annoying in your language. @euf @fabi94music

**Comment by euf** [comment]
@alejx IINA 0.0.13 Settings window looks much better now, thanks.
Several problems are still there, though:
- When the «Codec», «Network» or «Advanced» tabs are active, the **problem 1** happens (last tab hides under «**>>**" icon.
- **Problem 4** (placement of buttons in the «Login to Opensubtitles" window) hasn’t been solved.
- The same for **Problem 7** (Video Panel, aspect ratio input field is overlapping the selector).
- Video Filter Presets window is too small to fit some words (check #1098).
- The «Codec» tab looks a bit inaccurate.
![2017-10-13 3 42 57](https://user-images.githubusercontent.com/11754264/31525417-d21dca5c-afc8-11e7-8ce9-58f8d466da40.png)

**Comment by mewalton** [comment]
I'm seeing Issue 7 in the English version (or at least UK English).

<img width="369" alt="screen shot 2017-10-19 at 16 41 41" src="https://user-images.githubusercontent.com/980640/31780089-a1acb788-b4ec-11e7-9d60-d24d7f2ca8e4.png">

**Comment by euf** [comment]
@lhc70000 Any updates on the issue? Please notice that previously overlapping fields are now almost inaccessible (5:4 option for example). 
![2018-06-18 22 57 10](https://user-images.githubusercontent.com/11754264/41808643-392ba7a4-76e9-11e8-913a-0eed178159c1.png)

**Comment by lhc70000** [comment]
@euf They are scrollable.

**Comment by euf** [comment]
So it seems like almost all problems discussed earlier were solved, except the disappearing tabs.

![2018-06-24 13 35 22](https://user-images.githubusercontent.com/11754264/41818260-91818926-77b3-11e8-99f8-a2132ead9ea5.png)

The settings window layout has changed so much that I suggest fixing the last minor problem and marking this issue as closed.

**Comment by alejx** [comment]
My opinion is to change the segmented control into a pop up button. It will definitely solve the problem but the downside of it is the user will have to click twice to change aspect ratio. However I don't think it's a huge problem since very rare videos have unwanted aspect ratio so that we may not want to change it very often.
